
server:
  port: 8082

spring:
  application:
    name: product-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Optional: Management endpoints for health check
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.instaprepsai.product: DEBUG
