server:
  port: 8081

spring:
  application:
    name: user-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Optional: Management endpoints for health check
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.instaprepsai.user: DEBUG
