
server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            wiretap: true
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
              - id: user-service
                enabled: true
                uri: lb://user-service
                predicates:
                  - Path=/users/**
                #filters:
                #  - StripPrefix=1

              - id: product-service
                enabled: true
                uri: lb://product-service
                predicates:
                  - Path=/products/**
                #filters:
                #  - StripPrefix=1

                                
              - id: auth-service
                enabled: true
                uri: lb://auth-service
                predicates:
                  - Path=/auth/**
                #filters:
                #  - StripPrefix=1

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.http.client.reactive.ReactorClientHttpConnector: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunction: DEBUG
