
server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
              - id: user-service
                enabled: true
                uri: lb://user-service
                predicates:
                  - Path=/users/**
                #filters:
                #  - StripPrefix=1

              - id: product-service
                enabled: true
                uri: lb://product-service
                predicates:
                  - Path=/products/**
                #filters:
                #  - StripPrefix=1

                                
              - id: auth-service
                enabled: true
                uri: lb://auth-service
                predicates:
                  - Path=/auth/**
                #filters:
                #  - StripPrefix=1
                
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

